name: Repo pipeline

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
#   cancel-in-progress: true

on:
  push:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

    # types: [opened, reopened]
    # branches:
    #   - "**"
# env:
# ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
# ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
# GITHUB_PR_NUMBER: ${{ github.event.number || '' }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      # - name: Setup NodeJS
      #   uses: actions/setup-node@v2

      - name: Npm install
        uses: ./
        run: npm i

      - name: Run coverage
        run: npx hardhat tests
