name: Repo pipeline

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
#   cancel-in-progress: true

on:
  push:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

    # types: [opened, reopened]
    # branches:
    #   - "**"
# env:
# ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
# ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
# GITHUB_PR_NUMBER: ${{ github.event.number || '' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm install
          npx hardhat compile
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: public/

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: webpack artifacts
          path: public
      - name: npm install, and test
        run: |
          npm install
          npx hardhat coverage
        env:
          CI: true
  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     # - uses: actions/checkout@v2
  #     # - uses: ./

  #     # - name: Setup NodeJS
  #     #   uses: actions/setup-node@v2

  #     # - name: Npm install
  #     #   run: npm i

  #     - name: Run coverage
  #       run: |
  #         npm install
  #         npx hardhat tests
